#!/usr/bin/env python3
"""tripletTools choice-model recovery-sweep Condor workflow driver (Python
orchestrator).

Answers: when the choice model used to *fit* an embedding from triplet
judgments differs from the choice model that actually *generated* those
judgments, how much recovery error does that mismatch cost -- and does it
grow smoothly or fall off a cliff? Both models are drawn from the same
Student-t continuum (parameterized by alpha: finite alpha is a Student-t
kernel, alpha=1 is exactly Crowd Kernel with mu=1, alpha=Inf is the exact
Gaussian/gamma=0.5 limit), so this is one continuum being crossed with
itself, not eight unrelated methods.

Design: a single synthetic ground-truth embedding (hierarchical/multi-scale,
so choice models with different tail behavior have the best chance to
diverge) is simulated once. For each of len(alphas) *generating* alphas, one
triplet dataset is drawn from the ground truth. Every (generating alpha,
fitting alpha) pair is then an independent embedding fit -- recovering an
embedding from that one generating alpha's triplets using that one fitting
alpha's choice model -- scored by Procrustes distance back to the known
ground truth. With 8 alphas that is 64 completely independent fits, each
taking tens of minutes locally; an embarrassingly parallel workload, hence
Condor.

Runs in a single Condor stage plus local setup/aggregation:
  0. Simulate (local, not a Condor job): generate the ground-truth embedding
     and, for each generating alpha, one triplet dataset from it. Pure
     Python (stdlib `random`/`math` only, matching this repo's other
     orchestrators' minimal-dependency convention) -- no R or numpy needed
     for this step, so it runs directly on the submit node before anything
     is queued.
  1. Fit: one job per (generating alpha, fitting alpha) pair, submitted
     together as a single queue block. Each job reads its assigned triplet
     file and the ground-truth embedding, fits one embedding under its
     assigned fitting alpha, and scores recovery error via Procrustes
     distance -- writing a single-row result CSV.
  2. Aggregate (local, not a Condor job): once every fit job has finished,
     concatenate all per-pair result rows into results_long.csv and pivot
     into error_matrix.csv (rows = generating alpha, cols = fitting alpha).

Every fit job runs condor_recovery_fit.R (in this same directory) inside
the tripletTools container image via HTCondor's container universe -- no R
installation is needed on the submit node, only Python 3 and PyYAML.

Usage:
    python3 condor_recovery_sweep_workflow.py <params.yml>

<params.yml> follows recovery_sweep_params_template.yml in this same
directory. Unlike the other three workflows here, this one takes no input
data file -- the "data" is synthetic and generated by this script itself
from the config's synthetic-embedding settings.
"""
import argparse
import csv
import math
import random
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit(
        "PyYAML is required to read the config file. Install with:\n"
        "  pip install --user pyyaml"
    )

SCRIPT_DIR = Path(__file__).resolve().parent
CONDOR_RECOVERY_FIT_R = SCRIPT_DIR / "condor_recovery_fit.R"


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------

def get_config(config, field, default=None):
    value = config.get(field)
    return value if value is not None else default


def alpha_label(alpha):
    return "Inf" if math.isinf(alpha) else str(alpha)


# ---------------------------------------------------------------------------
# Stage 0: synthetic ground truth + per-generating-alpha triplet simulation
# (stdlib only -- deliberately no numpy dependency, see module docstring)
# ---------------------------------------------------------------------------

def make_synthetic_embedding(n_super, n_sub_per_super, n_items_per_sub,
                              super_radius, sub_offset, within_sd, seed, d=3):
    """Hierarchical, multi-scale ground truth in d dimensions: n_super
    widely separated superclusters, each with n_sub_per_super moderately
    separated subclusters, each with n_items_per_sub tightly packed items.
    Produces small (within-subcluster), medium (within-supercluster), and
    large (between-supercluster) true pairwise distances -- the regime
    where choice models with different tail behavior are expected to
    diverge most.

    d must match the `d` used for every recovery fit -- get.rep.dist()'s
    Procrustes comparison requires the ground truth and recovered
    embeddings to share the same dimensionality (see condor_recovery_fit.R
    and get_rep_dist.R's docs), so ground truth is generated at whatever
    dimensionality the fits themselves will use, not a fixed 3D."""
    rng = random.Random(seed)

    def unit_vec():
        v = [rng.gauss(0.0, 1.0) for _ in range(d)]
        norm = math.sqrt(sum(x * x for x in v))
        return [x / norm for x in v]

    super_centers = [[c * super_radius for c in unit_vec()] for _ in range(n_super)]

    items = []
    idx = 0
    for s in range(n_super):
        for _sub in range(n_sub_per_super):
            offset_dir = unit_vec()
            sub_center = [super_centers[s][k] + offset_dir[k] * sub_offset for k in range(d)]
            for _it in range(n_items_per_sub):
                idx += 1
                coords = [sub_center[k] + rng.gauss(0.0, within_sd) for k in range(d)]
                items.append((f"item{idx}", coords))
    return items


def choice_prob(dA2, dB2, alpha):
    """Student-t kernel choice probability (finite alpha; alpha=1 is exactly
    Crowd Kernel with mu=1), or its exact Gaussian/gamma=0.5 limit when
    alpha is infinite."""
    if math.isinf(alpha):
        return 1.0 / (1.0 + math.exp(0.5 * (dA2 - dB2)))
    tA = (1.0 + dA2 / alpha) ** (-(alpha + 1.0) / 2.0)
    tB = (1.0 + dB2 / alpha) ** (-(alpha + 1.0) / 2.0)
    return tA / (tA + tB)


def simulate_triplets(coords, alpha, n_triplets, seed):
    """coords: list of (n_items) coordinate lists, any dimensionality.
    Returns a list of (head, winner, loser) 0-based-index tuples."""
    rng = random.Random(seed)
    n_items = len(coords)
    d = len(coords[0])
    rows = []
    for _ in range(n_triplets):
        h = rng.randrange(n_items)
        a, b = rng.sample([i for i in range(n_items) if i != h], 2)
        dA2 = sum((coords[h][k] - coords[a][k]) ** 2 for k in range(d))
        dB2 = sum((coords[h][k] - coords[b][k]) ** 2 for k in range(d))
        p = choice_prob(dA2, dB2, alpha)
        if rng.random() < p:
            rows.append((h, a, b))
        else:
            rows.append((h, b, a))
    return rows


def write_ground_truth_csv(path, items):
    d = len(items[0][1])
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["item"] + [f"dim_{k}" for k in range(d)])
        for name, coords in items:
            writer.writerow([name] + list(coords))


def write_triplets_csv(path, rows):
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["head", "winner", "loser"])
        writer.writerows(rows)


def simulate_stage(work_dir, config):
    sim_dir = work_dir / "stage0_simulate"
    sim_dir.mkdir(parents=True, exist_ok=True)

    synth_cfg = config.get("synthetic_embedding") or {}
    n_super          = int(get_config(synth_cfg, "n_super", 5))
    n_sub_per_super  = int(get_config(synth_cfg, "n_sub_per_super", 2))
    n_items_per_sub  = int(get_config(synth_cfg, "n_items_per_sub", 5))
    super_radius     = float(get_config(synth_cfg, "super_radius", 12.0))
    sub_offset       = float(get_config(synth_cfg, "sub_offset", 2.5))
    within_sd        = float(get_config(synth_cfg, "within_sd", 0.3))
    seed             = int(config.get("seed", 1))
    d                = int(config["d"])

    items = make_synthetic_embedding(n_super, n_sub_per_super, n_items_per_sub,
                                      super_radius, sub_offset, within_sd, seed, d=d)
    gt_path = sim_dir / "ground_truth.csv"
    write_ground_truth_csv(gt_path, items)
    coords = [c for _name, c in items]

    n_triplets = int(get_config(config, "n_triplets_per_gen", 4000))
    triplet_paths = {}
    for gi, alpha in enumerate(config["alphas"]):
        label = alpha_label(alpha)
        rows = simulate_triplets(coords, alpha, n_triplets, seed=1000 + gi)
        path = sim_dir / f"triplets_gen{label}.csv"
        write_triplets_csv(path, rows)
        triplet_paths[label] = path

    print(f"[condor_recovery_sweep] Simulated {len(items)}-item ground truth and "
          f"{len(triplet_paths)} generating-alpha triplet sets ({n_triplets} triplets each) "
          f"in {sim_dir}")
    return gt_path, triplet_paths


# ---------------------------------------------------------------------------
# Submit-file generation and job execution (generic Condor helpers --
# duplicated from the other three orchestrator scripts in this directory by
# design: each Condor workflow here is meant to be self-contained, not to
# share a module between orchestrators)
# ---------------------------------------------------------------------------

def write_submit_file(path, *, container_image, arguments, transfer_input_files,
                       log, output, error, resources, initialdir,
                       queue_statement="queue\n"):
    content = f"""universe        = container
container_image = {container_image}

executable          = /usr/local/bin/Rscript
transfer_executable = False
arguments  = {arguments}

initialdir = {initialdir}

transfer_input_files    = {transfer_input_files}
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_cpus   = {resources.get("request_cpus", 1)}
request_memory = {resources.get("request_memory", "4GB")}
request_disk   = {resources.get("request_disk", "8GB")}

log    = {log}
output = {output}
error  = {error}

{queue_statement}"""
    path.write_text(content)


def submit_and_wait(submit_path, log_path, label):
    print(f"[condor_recovery_sweep] Submitting {label} ({submit_path.name})...")
    result = subprocess.run(["condor_submit", str(submit_path)],
                             capture_output=True, text=True)
    print(result.stdout.strip())
    if result.returncode != 0:
        sys.exit(f"condor_submit failed for {label}:\n{result.stderr}")

    print(f"[condor_recovery_sweep] Waiting for {label} to finish "
          f"(condor_wait {log_path})...")
    wait = subprocess.run(["condor_wait", str(log_path)])
    if wait.returncode != 0:
        sys.exit(
            f"condor_wait exited with status {wait.returncode} for {label}. "
            f"Check {log_path} and the corresponding .out/.err files for "
            "held or failed jobs (condor_q -hold, condor_q -better-analyze)."
        )


def queue_from_block(varnames, rows):
    lines = [f"queue {','.join(varnames)} from ("]
    lines += [f"  {','.join(str(v) for v in row)}" for row in rows]
    lines.append(")\n")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Stage 1: fit
# ---------------------------------------------------------------------------

def run_fit_stage(work_dir, gt_path, triplet_paths, config, resources, container_image):
    stage_dir = work_dir / "stage1_fit"
    stage_dir.mkdir(parents=True, exist_ok=True)

    d            = int(config["d"])
    max_epochs   = get_config(config, "max_epochs", 60000)
    tolerance    = get_config(config, "tolerance", 1e-4)
    tol_window   = get_config(config, "tol_window", 3000)
    device       = get_config(config, "device", "cpu")
    test_frac    = get_config(config, "test_frac", 0.1)
    seed         = int(config.get("seed", 1))

    alphas = config["alphas"]

    # Two variables per triplet file: *_src is where write_submit_file finds
    # the file to transfer (relative to this stage's initialdir, i.e.
    # reaching back into stage0_simulate/); *_name is the bare filename the
    # file lands under inside the job's sandbox after transfer (HTCondor
    # strips any directory component from transfer_input_files) -- same
    # pattern, and same rationale, as condor_group_diff_workflow.py's
    # embedding_a_src/embedding_a_name pair.
    #
    # Jobs indexed by position, not by (gen, fit) label strings, so
    # filenames stay simple regardless of how alpha values print.
    jobs = []  # (triplets_src, triplets_name, output_name, gen_label, fit_label, fit_seed)
    for gi, gen_alpha in enumerate(alphas):
        gen_label = alpha_label(gen_alpha)
        triplets_src_path = triplet_paths[gen_label]
        triplets_src = f"../stage0_simulate/{triplets_src_path.name}"
        for fi, fit_alpha in enumerate(alphas):
            fit_label = alpha_label(fit_alpha)
            output_name = f"result_gen{gi}fit{fi}.csv"
            fit_seed = seed + gi * 100 + fi
            jobs.append((triplets_src, triplets_src_path.name, output_name,
                         gen_label, fit_label, fit_seed))

    fixed_args = (
        "condor_recovery_fit.R --triplets=$(triplets_name) "
        f"--ground_truth={gt_path.name} "
        "--gen_alpha=$(gen_label) --fit_alpha=$(fit_label) --output=$(output_name) "
        f"--d={d} --seed=$(fit_seed) --test_frac={test_frac} "
        f"--max_epochs={max_epochs} --tolerance={tolerance} --tol_window={tol_window} "
        f"--device={device}"
    )

    submit_path = stage_dir / "fit.sub"
    write_submit_file(
        submit_path,
        container_image=container_image,
        arguments=fixed_args,
        transfer_input_files=f"{CONDOR_RECOVERY_FIT_R}, {gt_path}, $(triplets_src)",
        log=str(stage_dir / "fit.log"),
        output=str(stage_dir / "fit_$(Process).out"),
        error=str(stage_dir / "fit_$(Process).err"),
        resources=resources,
        initialdir=str(stage_dir),
        queue_statement=queue_from_block(
            ["triplets_src", "triplets_name", "output_name", "gen_label", "fit_label", "fit_seed"],
            jobs,
        ),
    )

    submit_and_wait(submit_path, stage_dir / "fit.log", "Stage 1 (recovery fits)")
    return stage_dir, jobs


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def aggregate_results(work_dir, stage1_dir, jobs, alphas):
    long_rows = []
    error_by_pair = {}
    for _triplets_src, _triplets_name, output_name, gen_label, fit_label, _fit_seed in jobs:
        path = stage1_dir / output_name
        if not path.exists():
            sys.exit(f"Expected fit output missing: {path} (gen={gen_label}, fit={fit_label}). "
                      "Check stage1_fit/fit_*.err for that job's failure.")
        with open(path, newline="") as f:
            row = next(csv.DictReader(f))
        long_rows.append(row)
        error_by_pair[(gen_label, fit_label)] = row["recovery_error"]

    long_path = work_dir / "results_long.csv"
    with open(long_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["gen_alpha", "fit_alpha", "recovery_error",
                                                "loss", "epoch"])
        writer.writeheader()
        writer.writerows(long_rows)

    labels = [alpha_label(a) for a in alphas]
    matrix_path = work_dir / "error_matrix.csv"
    with open(matrix_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([""] + [f"fit_{lbl}" for lbl in labels])
        for gen_lbl in labels:
            writer.writerow([f"gen_{gen_lbl}"] +
                             [error_by_pair.get((gen_lbl, fit_lbl), "") for fit_lbl in labels])

    return long_path, matrix_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("params", type=Path, help="YAML config file")
    args = parser.parse_args()

    if not args.params.exists():
        sys.exit(f"file not found: {args.params}")

    with open(args.params) as f:
        config = yaml.safe_load(f) or {}

    if "d" not in config:
        sys.exit("params.yml must set 'd' (the embedding dimensionality every fit uses).")
    if "alphas" not in config or not config["alphas"]:
        sys.exit("params.yml must set a non-empty 'alphas' list.")
    config["alphas"] = [float(a) for a in config["alphas"]]

    work_dir = Path(config.get("output_dir", "condor_recovery_sweep_output")).resolve()
    work_dir.mkdir(parents=True, exist_ok=True)

    condor_cfg = config.get("condor") or {}
    container_image = condor_cfg.get(
        "container_image",
        "docker://ghcr.io/knowledge-and-concepts-lab/triplettools:latest",
    )
    resources = condor_cfg.get("resources") or {}

    n_pairs = len(config["alphas"]) ** 2
    print(f"[condor_recovery_sweep] {len(config['alphas'])} alphas -> {n_pairs} "
          f"(generating, fitting) pairs, d={config['d']}")

    gt_path, triplet_paths = simulate_stage(work_dir, config)
    stage1_dir, jobs = run_fit_stage(work_dir, gt_path, triplet_paths, config,
                                      resources, container_image)
    long_path, matrix_path = aggregate_results(work_dir, stage1_dir, jobs, config["alphas"])

    manifest = [
        f"Run finished:    {__import__('datetime').datetime.utcnow().isoformat()}Z",
        f"config:          {args.params.resolve()}",
        f"alphas:          {config['alphas']}",
        f"n_pairs:         {n_pairs}",
        f"d:               {config['d']}",
        f"container_image: {container_image}",
        f"results_long:    {long_path}",
        f"error_matrix:    {matrix_path}",
    ]
    (work_dir / "run_manifest.txt").write_text("\n".join(manifest) + "\n")

    print(f"[condor_recovery_sweep] Done. {n_pairs} fits written to {long_path} and "
          f"{matrix_path}")


if __name__ == "__main__":
    main()
